# Generated by Django 4.1.3 on 2022-11-08 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='universityclasses',
            options={'verbose_name_plural': 'University Classes'},
        ),
        migrations.AlterField(
            model_name='universityclasses',
            name='duration',
            field=models.FloatField(blank=True, default=None),
        ),
    ]
