# Generated by Django 4.2 on 2023-04-27 18:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("school", "0002_comments"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
        migrations.DeleteModel(
            name="Comments",
        ),
    ]
