# Generated by Django 4.2 on 2023-04-28 03:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("school", "0007_alter_order_completed_alter_orderitem_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="transaction_id",
            field=models.CharField(max_length=80),
        ),
    ]
