# Generated by Django 4.2 on 2023-05-14 01:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("school", "0010_remove_order_product_order_product"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="product",
        ),
    ]
