# Generated by Django 4.2 on 2023-05-15 14:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("school", "0013_rename_product_order_products"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="products",
            new_name="product",
        ),
    ]
