# Generated by Django 4.2 on 2023-05-15 14:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("school", "0015_alter_order_product"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="product",
        ),
        migrations.AddField(
            model_name="order",
            name="product",
            field=models.ManyToManyField(blank=True, to="school.product"),
        ),
    ]
