# Generated by Django 4.2 on 2023-05-15 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("school", "0018_remove_order_products_alter_order_completed_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="product",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="school.product",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="completed",
            field=models.BooleanField(default=False),
        ),
    ]
